export const metadata = {
  title: "login",
  description: "Generated by Next.js",
};
export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
