export const metadata = {
  title: "Product",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <header>
        <p>this is Product page</p>
      </header>
      {children}
    </div>
  );
}
